tap 'caskroom/cask'
brew 'caskroom/cask/brew-cask'
cask 'java'
brew 'coreutils'
brew 'findutils'
brew 'bash'
brew 'wget', args: ['enable-iri']
brew 'vim', args: ['override-system-vi']
tap 'homebrew/dupes'
brew 'homebrew/dupes/grep'
tap 'josegonzalez/homebrew-php'
brew 'php55'
brew 'python'
brew 'python3'
brew 'mysql'
brew 'rename'
brew 'tree'
brew 'git'
brew 'ruby'

tap 'caskroom/versions'
cask 'alfred'
cask 'box-sync'
cask 'box-edit'
cask 'mysql-workbench'
cask 'adium'
cask 'caffeine'
cask 'iterm2'
cask 'google-chrome'
cask 'firefox'
cask 'sublime-text3'
cask 'the-unarchiver'
# Remove outdated versions from the cellar
